# Generated by Django 4.2.2 on 2023-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=30)),
                ('std_Roll', models.CharField(max_length=6)),
                ('std_Email', models.EmailField(max_length=30)),
                ('std_Dept', models.CharField(max_length=30)),
            ],
        ),
    ]
