# Generated by Django 4.2.2 on 2023-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Roll', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
                ('pasdate', models.DateField()),
                ('admDateTime', models.DateTimeField()),
            ],
        ),
    ]
